name: flutter_clean_arch
description: flutter post clean architecture.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #value equality
  equatable: ^2.0.5
  #functional programming
  dartz: ^0.10.1
  #bloc for state mangement
  flutter_bloc: ^8.1.3
  #service locator for dp injection
  get_it: ^7.6.4
  # for internet connection checking :)
  internet_connection_checker: ^1.0.0+1
  #locale storage
  shared_preferences: ^2.2.1
  #remote API
  dio: ^5.3.2
  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  